# Generated by Django 5.1.6 on 2025-04-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='profilepic',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profilepic',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
