# Generated by Django 5.1.6 on 2025-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_staffprofile_profilepic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
